version: "3"
services:

  cheat-server:
    image: ${IMAGE}:${META_TAG}
    container_name: ${CONTAINER_NAME}

    depends_on:
      - redis

    environment:
      - CHEATSH_CACHE_REDIS_HOST=redis

    ports:
      - "8002:8002"

    volumes:
      - ${PWD}/upstream:/home/abc/.cheat.sh/upstream
#      - ${PWD}/root/etc/services.d:/etc/services.d
#      - ${PWD}/root/etc/cont-init.d:/etc/cont-init.d

    environment:
      - PUID=${UID}
      - PGID=${GID}


  redis:
    image: redis:4-alpine
    container_name: cheat_redis_db
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]  # disable persistence
    volumes:
      - redis_data:/data

volumes:
  redis_data:

